server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /ws/ {
        proxy_pass https://agricares-production.up.railway.app;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host agricares-production.up.railway.app;
        proxy_ssl_server_name on;
        proxy_ssl_name agricares-production.up.railway.app;
    }
}
